# Generated by Django 4.2.4 on 2023-08-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0002_attendancemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='checkin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
