# Generated by Django 4.2.4 on 2023-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0004_checkoutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
