# Generated by Django 4.2.3 on 2023-08-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0005_userlogin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('long', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='SupFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniform', models.CharField(blank=True, choices=[('Apron', 'Apron'), ('Id-Card', 'Id-Card'), ('Leaflets', 'Leaflets'), ('Exam Pad', 'Exam Pad'), ('Folder', 'Folder')], max_length=100, null=True)),
                ('grooming', models.CharField(blank=True, choices=[('Combing', 'Combing'), ('Dress', 'Dress'), ('Shoes', 'Shoes'), ('Cleaniness', 'Cleaniness')], max_length=100, null=True)),
                ('ol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('po', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('sfm', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('sapp', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('leaf', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('dapp', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('script', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('confi', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10)),
                ('calls', models.CharField(blank=True, max_length=400, null=True)),
                ('ps', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('long', models.CharField(blank=True, max_length=100, null=True)),
                ('ts', models.CharField(blank=True, max_length=100, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='more.outletmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='more.userlogin')),
            ],
        ),
    ]
