# Generated by Django 4.2.3 on 2023-08-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0006_outletmodel_alter_userlogin_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='user',
        ),
    ]
