# Generated by Django 4.2.3 on 2023-08-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0008_attendancemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supformmodel',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutmodel',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supformmodel',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
