# Generated by Django 4.2.3 on 2023-08-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0009_attendancemodel_username_checkoutmodel_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supformmodel',
            name='grooming',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supformmodel',
            name='uniform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
