# Generated by Django 4.2.4 on 2023-09-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0010_alter_supformmodel_grooming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='flag',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
